about/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^about/$', views.AboutView.as_view(), name='about'),


]

contact/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^contact/$', views.ContactView.as_view(), name='contact'),

]

home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [

    url(r'^$', views.HomeView.as_view(), name='home'),

]

sw_project/urls.py
from django.conf.urls import url, include
from django.urls import include, path
from django.contrib import admin

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static
from users import views
from home import views




urlpatterns = [


    url(r'^admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('TeamMap/', include(('TeamMap.urls', 'TeamMap'), namespace='TeamMap')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('meetings/', include(('meetings.urls', 'meetings'), namespace='meetings')),
    path('about/', include(('about.urls', 'about'), namespace='about')),
    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),


    # url(r'^home/$', views.HomeView.as_view(), name='home'),
    # url(r'^home/$', include('Home.urls', name='home')),
    # url(r'^TeamMap/', include('TeamMap.urls', namespace = 'admin')),
    #url(r'^users/', include ('users.urls', namespace = 'users')),
    #url(r'^meetings/', include ('meetings.urls', namespace = 'meetings')),
    # url(r'^users/', include ('users.urls')),
    # url(r'^meetings/', include ('meetings.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# will check if in debug, and if yes, will attach to urlpatterns to serve up static files
urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.conf.urls import url
from . import views

from django.views.generic import TemplateView

#dot means same directory

urlpatterns = [
#/TeamMap/register




    url(r'^role/$', views.ChooseRoleView.as_view(), name='role'),

    url(r'^role/student/$', views.StudentSignUpView.as_view(), name='signup-student'),

    url(r'^role/mentor/$', views.MentorSignUpView.as_view(), name='signup-mentor'),






]
#
# from django.urls import include, path
#
# from classroom.views import classroom, students, teachers
#
# urlpatterns = [
#     path('', include('classroom.urls')),
#     path('accounts/', include('django.contrib.auth.urls')),
#     path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
#     path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
#     path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
# ]

contact/models.py
from django.db import models

# Create your models here.

contact/views.py
from django.views.generic import TemplateView


class ContactView(TemplateView):
    template_name = 'contact.html'

contact/templates/contact.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <title>About</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Raleway:400,700,900|Lato:400,900' %}" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/prettyphoto/css/prettyphoto.css' %}" rel="stylesheet">
  <link href="{% static 'lib/hover/hoverex-all.css' %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
    Template Name: Solid
    Template URL: https://templatemag.com/solid-bootstrap-business-template/
    Author: TemplateMag.com
    License: https://templatemag.com/license/
  ======================================================= -->
</head>

<body>

  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="index.html">SMALLWORLD</a>
      </div>
      <div class="navbar-collapse collapse navbar-right">
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'home:home' %}">HOME</a></li>
          <li><a href="{% url 'about:about' %}">WHO WE ARE</a></li>
         <li><a href="{% url 'contact:contact' %}">CONTACT</a></li>
          <li> <a href="{% url 'users:role' %}">JOIN NOW</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">PAGES <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="blog.html">BLOG</a></li>
              <li><a href="single-post.html">SINGLE POST</a></li>
              <li><a href="portfolio.html">PORTFOLIO</a></li>
              <li><a href="single-project.html">SINGLE PROJECT</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>

  <!-- *****************************************************************************************************************
	 BLUE WRAP
	 ***************************************************************************************************************** -->
  <div id="blue">
    <div class="container">
      <div class="row">
        <h3>About.</h3>
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /blue -->


  <!-- *****************************************************************************************************************
	 AGENCY ABOUT
	 ***************************************************************************************************************** -->

  <div class="container mtb">
    <div class="row">
      <div class="col-lg-6">
        <img class="img-responsive" src="{% static 'img/agency.jpg' %}" alt="">
      </div>

      <div class="col-lg-6">
        <h4>More About Our Agency.</h4>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
          It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
        <p>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <p>Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the
          undoubtable source.</p>
        <p><br/><a href="#" class="btn btn-theme">Contact Us</a></p>
      </div>
    </div>
  </div>

  <!-- *****************************************************************************************************************
	 TEEAM MEMBERS
	 ***************************************************************************************************************** -->

  <div class="container mtb">
    <div class="row centered">
      <h3 class="mb">MEET OUR TEAM</h3>

      <div class="col-lg-3 col-md-3 col-sm-3">
        <div class="he-wrap tpl6">
          <img src="{% static 'img/team/team01.jpg' %}" alt="">
          <div class="he-view">
            <div class="bg a0" data-animate="fadeIn">
              <h3 class="a1" data-animate="fadeInDown">Contact Me:</h3>
              <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-envelope"></i></a>
              <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-twitter"></i></a>
            </div>
            <!-- he bg -->
          </div>
          <!-- he view -->
        </div>
        <!-- he wrap -->
        <h4>Mark Webber</h4>
        <h5 class="ctitle">CEO</h5>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
        <div class="hline"></div>
      </div>

      <div class="col-lg-3 col-md-3 col-sm-3">
        <div class="he-wrap tpl6">
          <img src="{% static 'img/team/team02.jpg' %}" alt="">
          <div class="he-view">
            <div class="bg a0" data-animate="fadeIn">
              <h3 class="a1" data-animate="fadeInDown">Contact Me:</h3>
              <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-envelope"></i></a>
              <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-twitter"></i></a>
            </div>
            <!-- he bg -->
          </div>
          <!-- he view -->
        </div>
        <!-- he wrap -->
        <h4>Paul Jameson</h4>
        <h5 class="ctitle">LEAD DESIGNER</h5>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
        <div class="hline"></div>
      </div>

      <div class="col-lg-3 col-md-3 col-sm-3">
        <div class="he-wrap tpl6">
          <img src="{% static 'img/team/team03.jpg' %}" alt="">
          <div class="he-view">
            <div class="bg a0" data-animate="fadeIn">
              <h3 class="a1" data-animate="fadeInDown">Contact Me:</h3>
              <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-envelope"></i></a>
              <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-twitter"></i></a>
            </div>
            <!-- he bg -->
          </div>
          <!-- he view -->
        </div>
        <!-- he wrap -->
        <h4>Laura Sommers</h4>
        <h5 class="ctitle">LEAD DEVELOPER</h5>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
        <div class="hline"></div>
      </div>

      <div class="col-lg-3 col-md-3 col-sm-3">
        <div class="he-wrap tpl6">
          <img src="{% static 'img/team/team04.jpg' %}" alt="">
          <div class="he-view">
            <div class="bg a0" data-animate="fadeIn">
              <h3 class="a1" data-animate="fadeInDown">Contact Me:</h3>
              <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-envelope"></i></a>
              <a href="#" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-twitter"></i></a>
            </div>
            <!-- he bg -->
          </div>
          <!-- he view -->
        </div>
        <!-- he wrap -->
        <h4>Martin Blunt</h4>
        <h5 class="ctitle">MARKETING</h5>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
        <div class="hline"></div>
      </div>

    </div>
  </div>

  <!-- *****************************************************************************************************************
	 TESTIMONIALS
	 ***************************************************************************************************************** -->
  <div id="twrap">
    <div class="container centered">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <i class="fa fa-comment-o"></i>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
            It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
          <h4><br/>Marcel Newman</h4>
          <p>WEB DESIGNER</p>
        </div>
      </div>
    </div>
  </div>

  <!-- *****************************************************************************************************************
	 OUR CLIENTS
	 ***************************************************************************************************************** -->
  <div id="cwrap">
    <div class="container">
      <div class="row centered">
        <h3>OUR CLIENTS</h3>
        <div class="col-lg-3 col-md-3 col-sm-3">
          <img src="img/clients/client01.png" class="img-responsive">
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3">
          <img src="img/clients/client02.png" class="img-responsive">
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3">
          <img src="img/clients/client03.png" class="img-responsive">
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3">
          <img src="img/clients/client04.png" class="img-responsive">
        </div>
      </div>
    </div>
  </div>

  <!-- *****************************************************************************************************************
	 FOOTER
	 ***************************************************************************************************************** -->
  <div id="footerwrap">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <h4>About</h4>
          <div class="hline-w"></div>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
        </div>
        <div class="col-lg-4">
          <h4>Social Links</h4>
          <div class="hline-w"></div>
          <p>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
            <a href="#"><i class="fa fa-tumblr"></i></a>
          </p>
        </div>
        <div class="col-lg-4">
          <h4>Our Address</h4>
          <div class="hline-w"></div>
          <p>
            Some Ave, 987,<br/> 23890, New York,<br/> United States.<br/>
          </p>
        </div>

      </div>
    </div>
  </div>

  <div id="copyrights">
    <div class="container">
      <p>
        &copy; Copyrights <strong>Solid</strong>. All Rights Reserved
      </p>
      <div class="credits">
        <!--
          You are NOT allowed to delete the credit link to TemplateMag with free version.
          You can delete the credit link only if you bought the pro version.
          Buy the pro version with working PHP/AJAX contact form: https://templatemag.com/solid-bootstrap-business-template/
          Licensing information: https://templatemag.com/license/
        -->
        Created with Solid template by <a href="https://templatemag.com/">TemplateMag</a>
      </div>
    </div>
  </div>
  <!-- / copyrights -->

  <!-- JavaScript Libraries -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script src="lib/php-mail-form/validate.js"></script>
  <script src="lib/prettyphoto/js/prettyphoto.js"></script>
  <script src="lib/isotope/isotope.min.js"></script>
  <script src="lib/hover/hoverdir.js"></script>
  <script src="lib/hover/hoverex.min.js"></script>

  <!-- Template Main Javascript File -->
  <script src="js/main.js"></script>

</body>
</html>