TeamMap/urls.py
from django.conf.urls import url
from . import views #dot means same directory

# from TeamMap.views import students, mentors



urlpatterns = [
    # /TeamMap/ is the pattern, index references this pattern
    url(r'^$', views.IndexView.as_view(), name= 'index'), #how to set up index for each individual page

    # /TeamMap/team_id/ is the pattern- detail references this pattern
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name= 'detail' ), #detailview expects id

    # /TeamMap/team/add/ - don't need to make pk, after create it will be assigned pk
    url(r'team/add/$', views.TeamCreate.as_view(), name='team-add'),

    # /TeamMap/team/2/
    url(r'team/(?P<pk>[0-9]+)/$', views.TeamUpdate.as_view(), name='team-update'),

    # /TeamMap/team/2/delete - don't need to make pk, after create it will be assigned pk
    url(r'team/(?P<pk>[0-9]+)/delete/$', views.TeamDelete.as_view(), name='team-delete'),

    url(r'^team/(?P<teampk>[0-9]+)/join/$', views.TeamStudentCreateView.as_view(), name='team_student_create'),
    #teampk is same as pk, but when have foreignkey to 2 things, need to specficy (should specify)
    #updateview needsn another primary key



]

home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [

    url(r'^$', views.HomeView.as_view(), name='home'),

]

sw_project/urls.py
from django.conf.urls import url, include
from django.urls import include, path
from django.contrib import admin

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static
from users import views
from home import views




urlpatterns = [


    url(r'^admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('TeamMap/', include(('TeamMap.urls', 'TeamMap'), namespace='TeamMap')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('meetings/', include(('meetings.urls', 'meetings'), namespace='meetings')),
    path('about/', include(('about.urls', 'about'), namespace='about')),
    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),


    # url(r'^home/$', views.HomeView.as_view(), name='home'),
    # url(r'^home/$', include('Home.urls', name='home')),
    # url(r'^TeamMap/', include('TeamMap.urls', namespace = 'admin')),
    #url(r'^users/', include ('users.urls', namespace = 'users')),
    #url(r'^meetings/', include ('meetings.urls', namespace = 'meetings')),
    # url(r'^users/', include ('users.urls')),
    # url(r'^meetings/', include ('meetings.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# will check if in debug, and if yes, will attach to urlpatterns to serve up static files
urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.conf.urls import url
from . import views

from django.views.generic import TemplateView

#dot means same directory

urlpatterns = [
#/TeamMap/register




    url(r'^role/$', views.ChooseRoleView.as_view(), name='role'),

    url(r'^role/student/$', views.StudentSignUpView.as_view(), name='signup-student'),

    url(r'^role/mentor/$', views.MentorSignUpView.as_view(), name='signup-mentor'),






]
#
# from django.urls import include, path
#
# from classroom.views import classroom, students, teachers
#
# urlpatterns = [
#     path('', include('classroom.urls')),
#     path('accounts/', include('django.contrib.auth.urls')),
#     path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
#     path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
#     path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
# ]

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'home/home.html'

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <title>SmallWorld</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Raleway:400,700,900|Lato:400,900' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Playfair+Display+SC" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/prettyphoto/css/prettyphoto.css' %}" rel="stylesheet">
  <link href="{% static 'lib/hover/hoverex-all.css' %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
    Template Name: Solid
    Template URL: https://templatemag.com/solid-bootstrap-business-template/
    Author: TemplateMag.com
    License: https://templatemag.com/license/
  ======================================================= -->
</head>

<body>

  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="{% url 'home:home' %}">SMALLWORLD</a>
      </div>
      <div class="navbar-collapse collapse navbar-right">
        <ul class="nav navbar-nav">
          <li><a href="#">WHO WE ARE</a></li>
          <li><a href="#">CONTACT</a></li>
          <li> <a href="{% url 'login' %}">LOG IN</a></li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>

{% block content %} {% endblock %}

home/templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}

    {% if user.is_authenticated and user.is_student %}
    <h2> Hi {{ user.username }}! </h2>
<p><a href="{% url 'logout' %}">Logout</a></p>
    <h3> Join a team now!</h3>
<p><a href="{% url 'TeamMap:index' %}">Explore all teams.</a></p>
    <h3> Already part of a team? Go to your team profile. </h3>

    {% elif user.is_authenticated and user.is_mentor %}
    <h2> Hi {{ user.username }}! </h2>
<p><a href="{% url 'logout' %}">logout</a></p>
    <h3>Maybe you haven't created a team yet: Create a Team!</h3>
<p><a href="{% url 'TeamMap:team-add' %}">Create Team</a></p>
    <h3>Maybe you have created a team, go to your team profile.</h3>

{% else %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>SmallWorld</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Raleway:400,700,900|Lato:400,900' %}" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/prettyphoto/css/prettyphoto.css' %}" rel="stylesheet">
  <link href="{% static 'lib/hover/hoverex-all.css' %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
    Template Name: Solid
    Template URL: https://templatemag.com/solid-bootstrap-business-template/
    Author: TemplateMag.com
    License: https://templatemag.com/license/
  ======================================================= -->
</head>

<body>

  <!-- *****************************************************************************************************************
	 HEADERWRAP
	 ***************************************************************************************************************** -->
  <div id="headerwrap">
    <div class="container">
      <div class="row">

          <h1> High school students can solve real-world problems. </h1>
          <h3>Join a SmallWorld team <br> to begin solving.</h3>
          <h2>Create a <a href="{% url 'users:signup-student' %}">student account</a> or a <a href="{% url 'users:signup-mentor' %}">mentor account</a> today.</h2>
          <img src="{% static 'img/globe_purple_black.png' %}" class="img-responsive">


      </div>




    </div>
    <!-- /container -->
  </div>
  <!-- /headerwrap -->

  <!-- *****************************************************************************************************************
	 SmallWorld Teams
	 ***************************************************************************************************************** -->
  <div id="teaminfo">
    <div class="row">
      <h1> SmallWorld teams identify and solve a humanitarian problem over two semesters through our free web-based program. </h1>
      <h2> How are SmallWorld teams effective and impactful? </h2>
    </div>
    <div class="row">
      <div class="column"><img src="{% static 'img/identify_soln_2_250x250.jpg' %}" style="width:100%"> </div>
      <div class="column"><img src="{% static 'img/become_educated_250x250.jpg' %}" style="width:100%"> </div>
      <div class="column"><img src="{% static 'img/form_a_solution_250x250.jpg' %}" style="width:100%"> </div>
      <div class="column"><img src="{% static 'img/create_ab_250x250.jpg' %}" style="width:100%"> </div>
      <div class="column"><img src="{% static 'img/solve_250x250.jpg' %}" style="width:100%"> </div>
    </div>
  </div>
  <button type="button" class="btn btn-default">Begin solving.</button>
  </div>

  <!-- *****************************************************************************************************************
	 PORTFOLIO SECTION
	 ***************************************************************************************************************** -->


  <!-- *****************************************************************************************************************
	 MIDDLE CONTENT
	 ***************************************************************************************************************** -->

  <div class="container mtb">

  </div>



  <!-- *****************************************************************************************************************
	 FOOTER
	 ***************************************************************************************************************** -->


  <div id="copyrights">
    <div class="container">
      <p>
        &copy; Copyrights <strong>Solid</strong>. All Rights Reserved
      </p>
      <div class="credits">
        <!--
          You are NOT allowed to delete the credit link to TemplateMag with free version.
          You can delete the credit link only if you bought the pro version.
          Buy the pro version with working PHP/AJAX contact form: https://templatemag.com/solid-bootstrap-business-template/
          Licensing information: https://templatemag.com/license/
        -->
        Created with Solid template by <a href="https://templatemag.com/">TemplateMag</a>
      </div>
    </div>
  </div>
  <!-- / copyrights -->

  <!-- JavaScript Libraries -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script src="lib/php-mail-form/validate.js"></script>
  <script src="lib/prettyphoto/js/prettyphoto.js"></script>
  <script src="lib/isotope/isotope.min.js"></script>
  <script src="lib/hover/hoverdir.js"></script>
  <script src="lib/hover/hoverex.min.js"></script>

  <!-- Template Main Javascript File -->
  <script src="js/main.js"></script>

</body>
</html>

{% endif %}
{% endblock %}