TeamMap/urls.py
from django.conf.urls import url
from . import views #dot means same directory

# from TeamMap.views import students, mentors



urlpatterns = [
    # /TeamMap/ is the pattern, index references this pattern
    url(r'^$', views.IndexView.as_view(), name= 'index'), #how to set up index for each individual page

    # /TeamMap/team_id/ is the pattern- detail references this pattern
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name= 'detail' ), #detailview expects id

    # /TeamMap/team/add/ - don't need to make pk, after create it will be assigned pk
    url(r'team/add/$', views.TeamCreate.as_view(), name='team-add'),

    # /TeamMap/team/2/
    url(r'team/(?P<pk>[0-9]+)/$', views.TeamUpdate.as_view(), name='team-update'),

    # /TeamMap/team/2/delete - don't need to make pk, after create it will be assigned pk
    url(r'team/(?P<pk>[0-9]+)/delete/$', views.TeamDelete.as_view(), name='team-delete'),

    url(r'^team/(?P<teampk>[0-9]+)/join/$', views.TeamStudentCreateView.as_view(), name='team_student_create'),
    #teampk is same as pk, but when have foreignkey to 2 things, need to specficy (should specify)
    #updateview needsn another primary key



]

home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [

    url(r'^$', views.HomeView.as_view(), name='home'),

]

sw_project/urls.py
from django.conf.urls import url, include
from django.urls import include, path
from django.contrib import admin

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static
from users import views
from home import views




urlpatterns = [


    url(r'^admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('TeamMap/', include(('TeamMap.urls', 'TeamMap'), namespace='TeamMap')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('meetings/', include(('meetings.urls', 'meetings'), namespace='meetings')),
    path('about/', include(('about.urls', 'about'), namespace='about')),
    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),


    # url(r'^home/$', views.HomeView.as_view(), name='home'),
    # url(r'^home/$', include('Home.urls', name='home')),
    # url(r'^TeamMap/', include('TeamMap.urls', namespace = 'admin')),
    #url(r'^users/', include ('users.urls', namespace = 'users')),
    #url(r'^meetings/', include ('meetings.urls', namespace = 'meetings')),
    # url(r'^users/', include ('users.urls')),
    # url(r'^meetings/', include ('meetings.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# will check if in debug, and if yes, will attach to urlpatterns to serve up static files
urlpatterns += staticfiles_urlpatterns()

TeamMap/models.py
from django.db import models
from users.models import Mentor, Student
# This gets you the user class, which you can use in admin, views, anywhere you need the user model
from django.contrib.auth import get_user_model
# You can use settings to get a reference to the class name (a string) which can be used in ForeignKey fields
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import Permission

class Team(models.Model):
    name = models.CharField(max_length=30)
    location = models.CharField(max_length = 30)
    bigIssue = models.CharField(max_length= 30)
    level = models.IntegerField()
    team_logo = models.FileField()
    accepting_members = models.BooleanField(default=True)

    numMembers = models.IntegerField(default=0)
    #need to get rid of this as Team attribute in search field
    #summary data- alt is, every time want to know, look at number of related users
    mentor = models.OneToOneField(Mentor, on_delete=models.CASCADE)

    objects = models.Manager
    #each is column
    #each album has ID numer, goes up by 1 for each new
    #unique key = ID number

    class Meta:
        permissions = (
            ('create_team', 'Create a Team'),
            ('join_team', 'Join Team')
        )

    def get_absolute_url(self): #return details page (benchmarks) of team created
        return reverse('TeamMap:detail', kwargs={'pk': self.pk}) #pass in with pk, hidden in class Team
        #use pk of whatever team just created(viewed?)


    def __str__(self):
        return "{} {}".format(self.name, self.mentor, self.accepting_members)


class TeamStudent(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    student = models.OneToOneField(Student, on_delete=models.CASCADE)
    #many to many between students and teams

    def __str__(self):
        return "{} {}".format(self.team, self.student)

    # def get_absolute_url(self): #return details page (benchmarks) of team created
    #     return reverse('TeamMap:team_student_create', kwargs={'pk': self.pk}) #pass in with pk, hidden in class Team
        #use pk of whatever team just created(viewed?)


class Benchmark(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    infoProj = models.CharField(max_length = 1000)
    problemState = models.CharField(max_length=200)
    is_relevant = models.BooleanField(default=False)
    DoesNotExist = models.BooleanField(default=True)
    #foreign key has id number of whatever it belongs to
    #whenever delete album, delete whatever linked to it (on_delete=models.CASCADE)

    def __str__(self):
        return "Info Project: " + self.infoProj + " Problem Statement: " + self.problemState

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):

    is_student = models.BooleanField(default=False)
    is_mentor = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.username)
#     takes email and explicitly makes it a string

class Student(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return "student: {}".format(self.user)


class Mentor(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)


    def __str__(self):
        return "mentor: {}".format(self.user)

# fix this

TeamMap/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

# from TeamMap.models import (myUser, Student)


# class StudentSignUpForm(UserCreationForm):
#     class Meta(UserCreationForm.Meta):
#         model = User
#
#     def save(self, commit=True):
#         user = super.save(commit=False)
#         user.is_student = True
#         if commit:
#             user.save()
#         return user

TeamMap/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views import generic
from TeamMap.models import Team, TeamStudent
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from users.models import Mentor
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

#can create custom mixin in mixins.py
#inherit from mixin you care about, use it everywhere you want it

class IndexView(generic.ListView): #inherit from ListView
    template_name = 'TeamMap/index.html' #what template we are using to display albums- when get list of albums, plug into this template
    context_object_name = 'allTeams' #makes object_list = allTeams

    def get_queryset(self): #queryset function- query database for teams we want
        return Team.objects.all()

class DetailView(generic.DetailView): #data about 1 object
    model = Team #what model trying to get details for
    template_name = 'TeamMap/detail.html' #when you get the team, what template do you want me to plug into

class TeamCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView): #SWnote - this function will be used by mentors to create team
    model = Team
    fields = ['name', 'location', 'level', 'team_logo','accepting_members', 'bigIssue' ]#what field do you need user to fill out
    success_url = reverse_lazy('TeamMap:index')  #thought 'TeamMap' was https
    #reverse is used to get actual url from url name. called immediately when python file is parsed, when server starts up.
    #don't want to call reverse until django is up and running b/c it would fail
    #_lazy means won't be run until actually needs to be, until trying to redirect
    #reverse is mapping from names to urls

    def test_func(self):
        return self.request.user.is_mentor
    #     self.request= in a class based view, always have access to self.request. if you put login required, there is logged in user
    #     self.request.user is whoever is logged in- always

    def form_valid(self, form):
        # gets called when form validation passed
        #based on model, dj will generate form. for required fields, required on form
        self.object = form.save(commit=False)
        mentor = self.request.user.mentor
        self.object.mentor = mentor
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        # setting variables that you can access in the template
        # context = context template will be rendered in
        #a lot of default contexts- which is why you make the super call
        context = super(TeamCreate, self).get_context_data(**kwargs)
        #super is calling parent's get context data
        #actually calling parent of TeamCreate, actually passing CreateView
        # print (context)
        context['mentor'] = self.request.user.mentor
        return context

class TeamUpdate(UpdateView):  # SWnote - this function will be used by mentors to create team
    model = Team
    fields = ['name', 'location', 'numMembers', 'level', 'team_logo' ]  # what field do you need user to fill out

class TeamDelete(DeleteView):
    model = Team #after delete, where want to go?
    success_url = reverse_lazy('TeamMap:index')

class TeamStudentCreateView(generic.CreateView):
    model = TeamStudent
    fields = []  #have to put fields in, even if blank
    success_url = reverse_lazy('TeamMap:index')

    def _get_team(self):
        teampk = self.kwargs.get('teampk')
        team = Team.objects.filter(pk=teampk).first()
        return team
    # need helper function for level of code (not a necessity)
    # because get team involves 1)value from self.kwargs then 2)db look up on that
    # turn code into function -1) limit repetition 2) easier to understand
    # could have a get student

    def form_valid(self, form):
        self.object = form.save(commit=False)
        team = self._get_team()
        self.object.team = team
        student = self.request.user.student
        self.object.student = student
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(TeamStudentCreateView, self).get_context_data(**kwargs)
        context['team'] = self._get_team()
        return context

    #shift tab- tabs left

TeamMap/templates/TeamMap/detail.html
{% extends 'home/base.html' %}
{% block title %}Benchmark Details{% endblock %}
{% block teams_active %}active{% endblock %}

{% block content %}

<a href="{% url 'TeamMap:detail' team.id %}">
    <img src="{{ team.team_logo.url }} " class="img-responsive" >

</a>



<h1>{{team.name}}</h1>
<h3>{{team.location}}</h3>
<h3>{{team.mentor}}</h3>
<h3>{{team.student_set}}</h3>

{% if team.accepting_members == True %}
    <p><a href="{% url 'TeamMap:team_student_create' team.id %}">Join Now</a></p>
{% endif %}


{% for benchmark in team.benchmark_set.all %}
        {{benchmark.infoProj}}
        {{benchmark.problemState}}
        <!--{% if benchmark.is_relevant %}-->
            <!--<img src="#" />-->
        <!--{% endif %}-->
        <br>
{% endfor %}


{% endblock %}

TeamMap/templates/TeamMap/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10"></div>
            <span class="text-danger small">{{ field.errors }}</span>
    </div>
        <label class="control-label col-sm-2">{{ field.label_tag }} </label>
        <div class="col-sm-10">{{ field }}</div>
{% endfor %}

TeamMap/templates/TeamMap/index.html
{% extends 'home/base.html' %}

{% block content %}


    <h3> SmallWorld TeamMap </h3>

    <ul>
        {% for team in allTeams %}
          {% if team.accepting_members == True %}
        <li><a href = "{% url 'TeamMap:detail' team.id %}"> {{team.name}} <span class="glyphicon glyphicon-check"></span></a></li>
          {% else %}
        <li><a href = "{% url 'TeamMap:detail' team.id %}"> {{team.name}}</a></li>
        {% endif %}

    </ul>

{% endfor %}

{% endblock %}

TeamMap/templates/TeamMap/team_form.html
{% extends 'home/base.html' %}
{% block title %}Add a New Team{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
                        {% csrf_token %}
                        {% include 'TeamMap/form-template.html' %}
                        <!--#file will be simple template for how we want labels and form fields to look-->
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button type="submit" class="btn btn-success">Submit</button>
                             </div>
                         </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

TeamMap/templates/TeamMap/teamstudent_form.html
{% extends 'home/base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
        <h2>{{team.name}}</h2>
      <form method="post" novalidate>
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Join</button>
      </form>
    </div>
  </div>
{% endblock %}